const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger.json'
const endpointsFiles = ['./app.js']

const doc = {
    info: {
        title: 'HRMA-GVM API',
        version: "1.0.0",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: 'localhost:3005',
    basePath: '/',
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js'); // project's root file
  });

// swaggerAutogen(outputFile, endpointsFiles, doc)